version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: ride-sharing-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - ride-sharing-network
 
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ride-sharing-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - ride-sharing-network

 
  user-service:
    image: ride-sharing-system-user-service
    container_name: user-service
    ports:
      - "7072:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres    
    networks:
      - ride-sharing-network
    depends_on:
      - postgres
      
  driver-service:
    image: ride-sharing-system-driver-service
    container_name: driver-service
    ports:
      - "7073:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/driver_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - ride-sharing-network
    depends_on:
      - postgres

  ride-service:
    image: ride-sharing-system-ride-service
    container_name: ride-service
    ports:
      - "7071:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ride_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - ride-sharing-network
    depends_on:
      - postgres
      - kafka

  payment-service:
    image: ride-sharing-system-payment-service
    container_name: payment-service
    ports:
      - "7075:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - ride-sharing-network
    depends_on:
      - postgres
      - kafka

  billing-service:
    image: ride-sharing-system-billing-service
    container_name: billing-service
    ports:
      - "7076:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/billing_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - ride-sharing-network
    depends_on:
      - postgres
      - kafka

  notification-service:
    image: ride-sharing-system-notification-service
    container_name: notification-service
    ports:
      - "7074:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notification_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - ride-sharing-network
    depends_on:
      - postgres
      - kafka

networks:
  ride-sharing-network:
    driver: bridge
